language: php

php:
    - 7.2
    - 7.3
    - 7.4

matrix:
    include:
        - php: 7.3
          env: SYMFONY_REQUIRE=4.4.*
        - php: 7.4
          env: SYMFONY_REQUIRE=5.1.*

env:
    - SYMFONY_REQUIRE=3.4.*

before_install:
    - find ~/.phpenv -name xdebug.ini -delete
    - composer self-update
    - composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-main
    - composer update --prefer-source

install:
    - vendor/bin/simple-phpunit install

script:
    - vendor/bin/simple-phpunit
    - vendor/bin/php-cs-fixer fix --dry-run --diff

notifications:
    email: laupi.frpar@gmail.com
